spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartfridge
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: app.log