CREATE TABLE IF NOT EXISTS USERS
(
  ID SERIAL NOT NULL,
  LOGIN varchar(20) NOT NULL,
  FULL_NAME varchar(100),
  EMAIL varchar(200) NOT NULL,
  PASS varchar(200) NOT NULL,
  CREATION_DATE DATE,
  CONSTRAINT USERS_PKEY PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PRODUCT_DETAILS
(
  ID SERIAL NOT NULL,
  PRODUCT_NAME varchar(200),
  STORAGE_PERIOD INTEGER,
  CONSTRAINT PRODUCT_DETAILS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
  ID SERIAL NOT NULL,
  PRODUCT_DETAILS_ID INTEGER,
  USER_ID INTEGER,
  CREATION_DATE DATE,
  BEST_BEFORE_DATE DATE,
  CONSTRAINT PRODUCTS_PKEY PRIMARY KEY (id),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (PRODUCT_DETAILS_ID) REFERENCES PRODUCT_DETAILS(ID)
);
